baseURL: https://mikhailspirin.github.io/synths-of-life-blog/
languageCode: en-us
title: Synths Of Life
avatar: static/avatar.jpg
theme: "PaperMod"
paginate: 15


# menu:
#   main:
#     - name: Home
#       url: /
#       weight: 1

params:
  homeInfoParams:
    Title: Hi there wave
    Content: For Eurorack and synths DIYs and repairs


    # author: Mikhail Spirin
    # description: For Eurorack and synths DIYs and repairs
    # menu_item_separator: ❆

  socialIcons: # optional
    - name: "Github"
      url: "https://github.com/MikhailSpirin"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/mikhail-spirin-6b0b1837/"
    - name: "Instagram"
      url: "https://www.instagram.com/mixail.spirin/"